services:
  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared-iridiscencia
    restart: unless-stopped
    command: tunnel run
    env_file:
      - .env
    networks:
      - web
    mem_limit: 128m

networks:
  web:
    external: true
    name: iridiscencia-web-net
